version: '3.8'

services:
  backend:
    image: ic-backend
    ports:
      - "4321:4321"
    volumes:
      - ./backend/models:/app/models
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=4321
    restart: unless-stopped

  frontend:
    image: ic-frontend
    ports:
      - "1234:1234"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
